### ISSUE TITLE
Strict first chunk handling

### ISSUE THREAD

**Issue by nfroidure** [sindresorhus/first-chunk-stream#1]
I'd like to be able to only receive the n first chunks and being able to remove/keep/change it.

It seems impossible to do it with the current implementation, mainly because it is a Transform stream and not a Duplex one that's used under the hood.

Would you be open to a refactoring providing the following API:

```
var FirstChunk = require('first-chunk-stream');

var fisrtChunkStream = new FirstChunk({
  size: 7,
}, function(err, buf, cb) {
    // do something with the buffer
   // Call the cb with it in arg to have it passed through or not to just remove it
  cb(null, buf);
});

```

Using firstchunk()  to instanciate a new stream would also be possible. The ctor stuff would be unnecessary since the constructor would be directly available for extending it.

**Comment by sindresorhus** [comment]
> I'd like to be able to only receive the n first chunks and being able to remove/keep/change it.

You can already do this. See the example in the readme:

``` js
fs.createReadStream('unicorn.txt', {highWaterMark: 1})
    .pipe(firstChunkStream({minSize: 7}, function (chunk, enc, cb) {
        // modifies the chunk. drop this call to remove the chunk.
        this.push(chunk.toUpperCase());
        cb();
    }))
```

Or am I missing something?

**Comment by nfroidure** [comment]
Mainly performance issues. The fact to transmit data byte per byte really slowdown the overall pipeline imo. I don't have a test to prove it though but i think it is a logical conclusion since callbacks are called for every byte of a single file.

**Comment by sindresorhus** [comment]
>  The fact to transmit data byte per byte really slowdown the overall pipeline imo.

That's just an example. The default `highWaterMark` is a lot higher. And you can set even higher yourself.

> callbacks are called for every byte of a single file.

No, the callback is only called once.

**Comment by nfroidure** [comment]
Yep but if you want the n first bytes only, you'll have to set `highWaterMark` to n so the issue will remain.

For callbacks, i thought of stream internal callbacks (_transform _read _write etc...).

**Comment by sindresorhus** [comment]
Ok, then it's a bit unclear to me what you want, but I'm happy to receive PR improvements as long it preserves its original functionality ;)

**Comment by nfroidure** [comment]
Fair guys's gonna be fair ;)

Note that it will introduce breaking changes though.

**Comment by sindresorhus** [comment]
> Note that it will introduce breaking changes though.

That's ok.
